# -*- coding: utf-8 -*-
"""Potato Disease Classification using CNN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14oZC5QOom7btzHEEHMlWVriTeRB4Gsit

##Potato Disease Classification using CNN

You are provided with the **Potato Disease Dataset** from PlantVillage, which contains images of potato leaves classified into three categories:

- **Early_blight**: Leaves affected by early blight disease
- **Late_blight**: Leaves affected by late blight disease  
- **healthy**: Healthy potato leaves

Your objective is to build a **Convolutional Neural Network (CNN) from scratch** using PyTorch to classify potato leaves into these 3 disease categories.
Your work will be evaluated based on the completion of the following tasks:
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("mohammad2012191/q1-stage-3-2026")

print("Path to dataset files:", path)

"""# Part 1: Load and Prepare Data (4 points)

**Tasks:**

- Create a custom Dataset class or use ImageFolder (if applicable)
- Create the training and testing datasets, and their DataLoaders
- Use RandomRotation(15) Augmentation on the training dataset + Reize the images to 32x32
- Display some sample images with their labels
"""

import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from torchvision import transforms
import kagglehub
import os
import matplotlib.pyplot as plt
import numpy as np
import random
from torchvision.datasets import ImageFolder
from tqdm import tqdm
import torch.optim as optim

from torchvision.datasets import ImageFolder

MEAN = [0.485, 0.456, 0.406]
STD  = [0.229, 0.224, 0.225]

train_transform = transforms.Compose([
    transforms.Resize((32, 32)),
    transforms.RandomRotation(15),   # ✅ augmentation only for train
    transforms.ToTensor(),
    transforms.Normalize(mean=MEAN, std=STD),
])

test_transform = transforms.Compose([
    transforms.Resize((32, 32)),
    transforms.ToTensor(),
    transforms.Normalize(mean=MEAN, std=STD),
])


# Create dataset objects
train_dataset = ImageFolder(os.path.join(path, "PlantVillage", "train"), transform=train_transform)
valid_dataset = ImageFolder(os.path.join(path, "PlantVillage", "test"),  transform=test_transform)

# Create DataLoaders
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True,  num_workers=2)
valid_loader = DataLoader(valid_dataset, batch_size=32, shuffle=False, num_workers=2)

# Check a batch of images
images, labels = next(iter(train_loader))
print(f"Batch shape: {images.shape}, Labels: {labels}")
print("Classes:", train_dataset.classes)

import random
import numpy as np

# Create a function to visualize samples
def visualize_samples(dataset, num_samples=8, title="Dataset Samples"):

    # Select random indices
    indices = random.sample(range(len(dataset)), num_samples)

    # Calculate grid size
    cols = 4
    rows = (num_samples + cols - 1) // cols

    # Create the plot
    fig, axes = plt.subplots(rows, cols, figsize=(12, 3 * rows))
    axes = axes.flatten()

    for i, idx in enumerate(indices):
        # Get image and label
        image, label = dataset[idx]
        # Convert tensor to numpy for display
        if isinstance(image, torch.Tensor):
            image = image.permute(1, 2, 0).numpy()  # CHW -> HWC
        # Get class name
        class_name = dataset.classes[label]
        # Display image
        axes[i].imshow(image)
        axes[i].set_title(f"{class_name}\n(Label: {label})", fontsize=10)
        axes[i].axis('off')
    # Hide any unused subplots
    for i in range(num_samples, len(axes)):
        axes[i].axis('off')

    plt.suptitle(title, fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.show()


# Visualize training samples
visualize_samples(train_dataset, num_samples=8, title="Training Dataset Samples")

"""# Part 2: Build the CNN Model (3 points)

**Tasks:**

Build a CNN from scratch with the following specifications:

- Create a CNN model class with **5 convolutional layers**
- Bonus: Add **BatchNormalization** after each convolutional layer

"""

import torch.nn as nn
import torch

class CNNModel(nn.Module):
    def __init__(self):
        super(CNNModel, self).__init__()

        # Convolutional Layers
        self.conv1 = nn.Conv2d(in_channels=3,   out_channels=16,  kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(in_channels=16,  out_channels=32,  kernel_size=3, padding=1)
        self.conv3 = nn.Conv2d(in_channels=32,  out_channels=64,  kernel_size=3, padding=1)
        self.conv4 = nn.Conv2d(in_channels=64,  out_channels=128, kernel_size=3, padding=1)
        self.conv5 = nn.Conv2d(in_channels=128, out_channels=256, kernel_size=3, padding=1)

        # Bonus: BatchNorm after each conv
        self.bn1 = nn.BatchNorm2d(16)
        self.bn2 = nn.BatchNorm2d(32)
        self.bn3 = nn.BatchNorm2d(64)
        self.bn4 = nn.BatchNorm2d(128)
        self.bn5 = nn.BatchNorm2d(256)

        # Activation
        self.relu = nn.ReLU()

        # Pooling Layer
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)

        # Fully Connected Layers
        # after 5 pools: 32->16->8->4->2->1  => feature map 1x1 with 256 channels
        self.fc1 = nn.Linear(256 * 1 * 1, 512)
        self.fc2 = nn.Linear(512, 3)  # 3 classes: Early_blight, Late_blight, healthy

    def forward(self, x):
        x = self.pool(self.relu(self.bn1(self.conv1(x))))
        x = self.pool(self.relu(self.bn2(self.conv2(x))))
        x = self.pool(self.relu(self.bn3(self.conv3(x))))
        x = self.pool(self.relu(self.bn4(self.conv4(x))))
        x = self.pool(self.relu(self.bn5(self.conv5(x))))

        # Flatten
        x = x.reshape(x.size(0), -1)

        # Fully Connected Layers
        x = self.relu(self.fc1(x))
        x = self.fc2(x)  # logits

        return x  # No softmax here because CrossEntropyLoss expects logits

"""# Part 3: Training and Validation Functions

**Tasks:**

- Define the training loop function
- Define the validation loop function
"""

def train_one_epoch(model, dataloader, criterion, optimizer, device):
    model.train()
    total_loss = 0.0
    correct = 0
    total = 0

    for images, labels in tqdm(dataloader, leave=False):
        images, labels = images.to(device), labels.to(device)

        outputs = model(images)
        loss = criterion(outputs, labels)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        bs = labels.size(0)
        total_loss += loss.item() * bs

        predictions = outputs.argmax(dim=1)
        correct += (predictions == labels).sum().item()
        total += bs

    avg_loss = total_loss / total
    accuracy = 100.0 * correct / total
    return avg_loss, accuracy


@torch.no_grad()
def validate(model, dataloader, criterion, device):
    model.eval()
    total_loss = 0.0
    correct = 0
    total = 0

    for images, labels in dataloader:
        images, labels = images.to(device), labels.to(device)

        outputs = model(images)
        loss = criterion(outputs, labels)

        bs = labels.size(0)
        total_loss += loss.item() * bs

        predictions = outputs.argmax(dim=1)
        correct += (predictions == labels).sum().item()
        total += bs

    avg_loss = total_loss / total
    accuracy = 100.0 * correct / total
    return avg_loss, accuracy

"""# Part 4: Training

**Tasks:**

- Set up device, model, loss function, and optimizer
- Train the model
- Plot the training and validation losses and training and validation accuracy
"""

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = CNNModel().to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

num_epochs = 10

train_losses = []
val_losses = []
train_accuracies = []
val_accuracies = []

for epoch in range(num_epochs):
    train_loss, train_accuracy = train_one_epoch(model, train_loader, criterion, optimizer, device)
    val_loss, val_accuracy = validate(model, valid_loader, criterion, device)

    train_losses.append(train_loss)
    val_losses.append(val_loss)
    train_accuracies.append(train_accuracy)
    val_accuracies.append(val_accuracy)

    print(f"Epoch {epoch+1}/{num_epochs}: "
          f"Train Loss={train_loss:.4f}, Train Accuracy={train_accuracy:.2f}%, "
          f"Val Loss={val_loss:.4f}, Val Accuracy={val_accuracy:.2f}%")

"""# Part 5: Residual Connection

**Task:**

Now let's see if we can improve our model with a residual connection!

1. **Redefine the CNN model** but add a **residual (skip) connection** from the **2nd convolutional layer** to the **4th convolutional layer**
   - You can use either **summation** OR **concatenation** for the skip connection
   - Note: You might need to use pooling to match the size of the skip connection with the 3rd layer output before concatenation!

2. **Retrain** the model with the residual connection
3. Plot the training and validation losses and training and validation accuracy
"""

class CNNModelResidual(nn.Module):
    def __init__(self):
        super(CNNModelResidual, self).__init__()

        # Convolutional Layers
        self.conv1 = nn.Conv2d(3,   16,  3, padding=1)
        self.conv2 = nn.Conv2d(16,  32,  3, padding=1)
        self.conv3 = nn.Conv2d(32,  64,  3, padding=1)
        self.conv4 = nn.Conv2d(64,  128, 3, padding=1)
        self.conv5 = nn.Conv2d(128, 256, 3, padding=1)

        # BatchNorm (bonus)
        self.bn1 = nn.BatchNorm2d(16)
        self.bn2 = nn.BatchNorm2d(32)
        self.bn3 = nn.BatchNorm2d(64)
        self.bn4 = nn.BatchNorm2d(128)
        self.bn5 = nn.BatchNorm2d(256)

        self.relu = nn.ReLU()
        self.pool = nn.MaxPool2d(2, 2)

        # Skip adapters: (B,32,8,8) -> (B,128,2,2)
        self.skip_pool = nn.MaxPool2d(kernel_size=4, stride=4)  # 8x8 -> 2x2
        self.skip_conv = nn.Conv2d(32, 128, kernel_size=1)       # 32 -> 128

        # Fully connected
        self.fc1 = nn.Linear(256 * 1 * 1, 512)
        self.fc2 = nn.Linear(512, 3)

    def forward(self, x):
        x = self.pool(self.relu(self.bn1(self.conv1(x))))   # (B,16,16,16)
        x2 = self.pool(self.relu(self.bn2(self.conv2(x))))  # (B,32,8,8) save for skip
        x = self.pool(self.relu(self.bn3(self.conv3(x2))))  # (B,64,4,4)
        x4 = self.pool(self.relu(self.bn4(self.conv4(x))))  # (B,128,2,2)

        # Residual SUM from conv2 output to conv4 output
        skip = self.skip_conv(self.skip_pool(x2))           # (B,128,2,2)
        x4 = x4 + skip                                      # SUM

        x = self.pool(self.relu(self.bn5(self.conv5(x4))))  # (B,256,1,1)

        x = x.reshape(x.size(0), -1)
        x = self.relu(self.fc1(x))
        x = self.fc2(x)                                     # logits
        return x

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = CNNModelResidual().to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)
num_epochs = 10

train_losses = []
val_losses = []
train_accuracies = []
val_accuracies = []

for epoch in range(num_epochs):
    train_loss, train_acc = train_one_epoch(model, train_loader, criterion, optimizer, device)
    val_loss, val_acc = validate(model, valid_loader, criterion, device)

    train_losses.append(train_loss)
    val_losses.append(val_loss)
    train_accuracies.append(train_acc)
    val_accuracies.append(val_acc)

    print(f"Epoch {epoch+1}/{num_epochs}: "
          f"Train Loss={train_loss:.4f}, Train Acc={train_acc:.2f}% | "
          f"Val Loss={val_loss:.4f}, Val Acc={val_acc:.2f}%")

epochs = np.arange(1, num_epochs + 1)

plt.figure(figsize=(7,5))
plt.plot(epochs, train_losses, label="Train Loss")
plt.plot(epochs, val_losses, label="Val Loss")
plt.title("Training vs Validation Loss (Residual Sum)")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(7,5))
plt.plot(epochs, train_accuracies, label="Train Accuracy")
plt.plot(epochs, val_accuracies, label="Val Accuracy")
plt.title("Training vs Validation Accuracy (Residual Sum)")
plt.xlabel("Epoch")
plt.ylabel("Accuracy (%)")
plt.legend()
plt.grid(True)
plt.show()