# -*- coding: utf-8 -*-
"""Multi-Class Segmentation for Underwater Imagery

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-9X6Fu3z2DUOhQglTAtm_EWioo6fy1cC

# **Multi-Class Segmentation for Underwater Imagery**

In this question, you should finetune a **pretrained U-Net** model for **multi-class segmentation** of underwater images. Your segmentation model will classify each pixel into **one of 8 classes**.

**Dataset:** SUIM (Semantic Segmentation of Underwater Imagery)

| Object Category | Class ID |
|----------------|----------|
| Background (waterbody) | 0 |
| Human divers | 1 |
| Aquatic plants and sea-grass | 2 |
| Wrecks and ruins | 3 |
| Robots (AUVs/ROVs/instruments) | 4 |
| Reefs and invertebrates | 5 |
| Fish and vertebrates | 6 |
| Sea-floor and rocks | 7 |

Complete the code cells below.

---
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("mohammad2012191/q3-stage3-2026")

print("Path to dataset files:", path)

"""## **TASK 1: Dataset Class**
- Build a custom dataset class to load images and masks.
- Use Dataloaders to prepare your data.
- Display some images and their corresponding masks.


"""

def remap_mask(mask):
    # Remaps a mask's pixel values to a consecutive range starting at 0
    mask = mask.long()
    unique_values = torch.unique(mask)
    remapped_mask = torch.zeros_like(mask)

    for new_val, old_val in enumerate(sorted(unique_values.tolist())):
        remapped_mask[mask == old_val] = new_val

    return remapped_mask

import os
import glob
import random
import numpy as np
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from PIL import Image
import torchvision.transforms as transforms
import torch.optim as optim
from tqdm import tqdm

import kagglehub

class SegDataset(Dataset):
    def __init__(self, image_dir, mask_dir, start=0, end=None, transform=None, target_transform=None):
        # Sort full lists first
        self.image_paths = sorted(glob.glob(os.path.join(image_dir, "*.jpg")))
        self.mask_paths  = sorted(glob.glob(os.path.join(mask_dir, "*.png")))

        if end is None:
            end = len(self.image_paths)

        # Slice AFTER sorting (this makes train/test split correct)
        self.image_paths = self.image_paths[start:end]
        self.mask_paths  = self.mask_paths[start:end]

        self.transform = transform
        self.target_transform = target_transform

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        image = Image.open(self.image_paths[idx]).convert("RGB")
        mask  = Image.open(self.mask_paths[idx]).convert("L")

        if self.transform:
            image = self.transform(image)

        if self.target_transform:
            mask = self.target_transform(mask)

        # IMPORTANT: SUIM classes are already 0..7
        # mask from PILToTensor is (1,H,W) -> make it (H,W)
        mask = mask.squeeze(0).long()

        return image, mask

from torch.utils.data import DataLoader
from torch import nn

# Define transforms for images and masks
image_transforms = transforms.Compose([
    transforms.Resize((64, 64)),  # Resize BEFORE ToTensor
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225])
])

mask_transforms = transforms.Compose([
    transforms.Resize((64, 64), interpolation=transforms.InterpolationMode.NEAREST),
    transforms.PILToTensor(),  # -> (1,H,W) values preserved (nearest)
])

train_dataset = SegDataset(os.path.join(path, "dataset", "images"), os.path.join(path, "dataset", "masks"), start=0, end = 160, transform=image_transforms, target_transform=mask_transforms)
test_dataset = SegDataset(os.path.join(path, "dataset", "images"), os.path.join(path, "dataset", "masks"), start=160, end = 201, transform=image_transforms, target_transform=mask_transforms)


# Create Train & Test DataLoaders
train_loader = DataLoader(train_dataset, batch_size=4, shuffle=True, num_workers=2)
test_loader = DataLoader(test_dataset, batch_size=4, shuffle=False, num_workers=2)

# Check dataset sizes
print(f"Training Samples: {len(train_dataset)}, Testing Samples: {len(test_dataset)}")

def denormalize(img_tensor):
    mean = np.array([0.485, 0.456, 0.406])
    std  = np.array([0.229, 0.224, 0.225])
    img = img_tensor.cpu().numpy().transpose(1, 2, 0)
    img = img * std + mean
    img = np.clip(img, 0, 1)
    return img

# Display some images with masks
for i in range(3):
    img, mask = train_dataset[i]
    fig, axes = plt.subplots(1, 2, figsize=(10, 5))

    axes[0].imshow(denormalize(img))
    axes[0].set_title("Image")
    axes[0].axis("off")

    # show mask as (H,W) and fix color range 0..7
    axes[1].imshow(mask.cpu(), cmap="gray", vmin=0, vmax=7)
    axes[1].set_title("Segmentation Mask")
    axes[1].axis("off")

    plt.tight_layout()
    plt.show()

"""## **TASK 2: Model Class**
- **Use a pretrained U-Net** (from `segmentation_models_pytorch`) with "efficientnet-b1" as an encoder.
"""

!pip install -q segmentation_models_pytorch

import segmentation_models_pytorch as smp

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = smp.Unet(
    encoder_name="efficientnet-b1",
    encoder_weights="imagenet",
    in_channels=3,
    classes=8
).to(device)

"""## **TASK 3: Training and Validation Loops**
- Define the training and validation loops.
"""

def train_one_epoch(model, dataloader, criterion, optimizer, device):
    model.train()
    total_loss = 0.0
    total_pixels = 0

    for images, masks in tqdm(dataloader, leave=False):
        images = images.to(device)
        masks  = masks.to(device)  # masks: (B,H,W) long

        outputs = model(images)    # outputs: (B,8,H,W) logits
        loss = criterion(outputs, masks)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        bs = images.size(0)
        total_loss += loss.item() * bs
        total_pixels += bs

    return total_loss / total_pixels


@torch.no_grad()
def validate(model, dataloader, criterion, device):
    model.eval()
    total_loss = 0.0
    total_pixels = 0

    for images, masks in dataloader:
        images = images.to(device)
        masks  = masks.to(device)

        outputs = model(images)
        loss = criterion(outputs, masks)

        bs = images.size(0)
        total_loss += loss.item() * bs
        total_pixels += bs

    return total_loss / total_pixels

"""## **TASK 4: Running Training**
- Define the loss and the optimizer.
- Train the model.
- Print the training and validation losses.
- Plot loss curve.
"""

criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.parameters(), lr=0.0001)

num_epochs = 10
train_losses = []
val_losses = []

for epoch in range(num_epochs):
    train_loss = train_one_epoch(model, train_loader, criterion, optimizer, device)
    val_loss   = validate(model, test_loader, criterion, device)

    train_losses.append(train_loss)
    val_losses.append(val_loss)

    print(f"Epoch {epoch+1}/{num_epochs}: Train Loss = {train_loss:.4f}, Val Loss = {val_loss:.4f}")

plt.figure(figsize=(7, 5))
plt.plot(range(1, num_epochs+1), train_losses, label="Train Loss", marker='o')
plt.plot(range(1, num_epochs+1), val_losses, label="Validation Loss", marker='o')
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.title("Training and Validation Loss")
plt.legend()
plt.grid(True)
plt.show()

"""## **TASK 5: Visualizing Predictions**
- Visualize your model's predictions against the ground truth for several images.
"""

model.eval()

test_samples = random.sample(range(len(test_dataset)), 8)

for idx in test_samples:
    img, mask = test_dataset[idx]

    with torch.no_grad():
        pred = model(img.unsqueeze(0).to(device))      # (1,8,H,W)
        pred_mask = pred.argmax(dim=1).cpu().squeeze() # (H,W)

    fig, axes = plt.subplots(1, 3, figsize=(15, 5))

    axes[0].imshow(denormalize(img))
    axes[0].set_title("Original Image")
    axes[0].axis("off")

    axes[1].imshow(mask.cpu(), cmap="gray", vmin=0, vmax=7)
    axes[1].set_title("Ground Truth Mask")
    axes[1].axis("off")

    axes[2].imshow(pred_mask, cmap="gray", vmin=0, vmax=7)
    axes[2].set_title("Predicted Mask")
    axes[2].axis("off")

    plt.tight_layout()
    plt.show()