# -*- coding: utf-8 -*-
"""Water Body Segmentation from Satellite Imagery

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iv4ccHqJwgilztgoQ-tNeZzetWohsIfl

# Water Body Segmentation from Satellite Imagery

## Dataset Overview
This dataset contains **satellite images** of landscapes along with their corresponding **binary segmentation masks**.
- **Images**: RGB satellite photos of various terrains.
- **Masks**: Binary images where **white pixels (1)** = water, **black pixels (0)** = non-water.

## Pipeline
1. Custom Dataset class with train/val split
2. U-Net with EfficientNet-B1 encoder (pretrained on ImageNet)
3. Training & validation loops with loss + IoU metric
4. Visualization of predictions vs ground truth
"""

import os
os.environ["KAGGLEHUB_CACHE"] = "/content/data"

import glob
import random
import numpy as np
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from PIL import Image
import torchvision.transforms as transforms
from tqdm import tqdm

import kagglehub

"""## Part 1: Download Dataset

"""

path = kagglehub.dataset_download("franciscoescobar/satellite-images-of-water-bodies")
print("Dataset path:", path)

"""## Part 2: Custom Dataset Class

"""

class WaterBodyDataset(Dataset):
    def __init__(self, image_dir, mask_dir, start=0, end=None,
                 transform=None, target_transform=None):

        all_image_paths = sorted(glob.glob(os.path.join(image_dir, "*.jpg")))
        all_mask_paths  = sorted(glob.glob(os.path.join(mask_dir,  "*.jpg")))

        # We sort so that image[i] always matches mask[i]
        if end is None:
            end = len(all_image_paths)

        self.image_paths = all_image_paths[start:end]
        self.mask_paths  = all_mask_paths[start:end]
        self.transform        = transform
        self.target_transform = target_transform

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        image = Image.open(self.image_paths[idx]).convert("RGB")
        mask  = Image.open(self.mask_paths[idx]).convert("L")

        if self.transform:
            image = self.transform(image)
        if self.target_transform:
            mask = self.target_transform(mask)

        # Binarize: PILToTensor gives (1,H,W) 0/255 -> 0/1
        mask = (mask > 0.5).long().squeeze(0)  # (H, W)
        return image, mask

"""## Part 3: Transforms & DataLoaders

"""

image_transforms = transforms.Compose([
    transforms.Resize((128, 128)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225])
])

mask_transforms = transforms.Compose([
    transforms.Resize((128, 128), interpolation=transforms.InterpolationMode.NEAREST),
    transforms.PILToTensor(),
    transforms.ConvertImageDtype(torch.float32),
])

image_dir = os.path.join(path, "Water Bodies Dataset", "Images")
mask_dir  = os.path.join(path, "Water Bodies Dataset", "Masks")

total = len(sorted(glob.glob(os.path.join(image_dir, "*.jpg"))))
split = int(total * 0.85)

train_dataset = WaterBodyDataset(image_dir, mask_dir, start=0, end=split,
                                 transform=image_transforms, target_transform=mask_transforms)
val_dataset   = WaterBodyDataset(image_dir, mask_dir, start=split, end=total,
                                 transform=image_transforms, target_transform=mask_transforms)

train_loader = DataLoader(train_dataset, batch_size=8, shuffle=True,  num_workers=2)
val_loader   = DataLoader(val_dataset,   batch_size=8, shuffle=False, num_workers=2)

print(f"Train: {len(train_dataset)} | Val: {len(val_dataset)}")

"""## Part 4: Visualize Samples

"""

def denormalize(tensor):
    mean = np.array([0.485, 0.456, 0.406])
    std  = np.array([0.229, 0.224, 0.225])
    img  = tensor.cpu().numpy().transpose(1, 2, 0)
    img  = img * std + mean
    return np.clip(img, 0, 1)

fig, axes = plt.subplots(3, 2, figsize=(8, 12))
for i in range(3):
    img, mask = train_dataset[i]
    axes[i][0].imshow(denormalize(img))
    axes[i][0].set_title("Satellite Image")
    axes[i][0].axis("off")
    axes[i][1].imshow(mask.cpu(), cmap="gray", vmin=0, vmax=1)
    axes[i][1].set_title("Water Mask (white = water)")
    axes[i][1].axis("off")
plt.tight_layout()
plt.show()

"""## Part 5: Load U-Net Model

"""

!pip install -q segmentation_models_pytorch

import segmentation_models_pytorch as smp

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = smp.Unet(
    encoder_name="efficientnet-b1",
    encoder_weights="imagenet",
    in_channels=3,
    classes=2  # binary: water vs non-water
).to(device)

print(f"Model loaded on {device}")

"""## Part 6: IoU Metric & Training / Validation Functions

"""

def compute_iou(preds, masks, num_classes=2):
    """Mean IoU over all classes."""
    iou_list = []
    preds = preds.cpu()
    masks = masks.cpu()
    for cls in range(num_classes):
        pred_c = (preds == cls)
        mask_c = (masks == cls)
        intersection = (pred_c & mask_c).sum().float()
        union        = (pred_c | mask_c).sum().float()
        if union == 0:
            iou_list.append(torch.tensor(1.0))
        else:
            iou_list.append(intersection / union)
    return torch.stack(iou_list).mean().item()


def train_one_epoch(model, dataloader, criterion, optimizer, device):
    model.train()
    total_loss = 0.0
    total_iou  = 0.0
    n = 0
    for images, masks in tqdm(dataloader, leave=False):
        images, masks = images.to(device), masks.to(device)
        outputs = model(images)
        loss    = criterion(outputs, masks)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        preds = outputs.argmax(dim=1)
        total_loss += loss.item() * images.size(0)
        total_iou  += compute_iou(preds, masks) * images.size(0)
        n += images.size(0)
    return total_loss / n, total_iou / n


@torch.no_grad()
def validate(model, dataloader, criterion, device):
    model.eval()
    total_loss = 0.0
    total_iou  = 0.0
    n = 0
    for images, masks in dataloader:
        images, masks = images.to(device), masks.to(device)
        outputs = model(images)
        loss    = criterion(outputs, masks)
        preds = outputs.argmax(dim=1)
        total_loss += loss.item() * images.size(0)
        total_iou  += compute_iou(preds, masks) * images.size(0)
        n += images.size(0)
    return total_loss / n, total_iou / n

"""## Part 7: Train the Model

"""

criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.parameters(), lr=1e-4)

num_epochs = 10
train_losses, val_losses = [], []
train_ious,   val_ious   = [], []

for epoch in range(num_epochs):
    t_loss, t_iou = train_one_epoch(model, train_loader, criterion, optimizer, device)
    v_loss, v_iou = validate(model, val_loader, criterion, device)

    train_losses.append(t_loss);  val_losses.append(v_loss)
    train_ious.append(t_iou);     val_ious.append(v_iou)

    print(f"Epoch {epoch+1}/{num_epochs} | "
          f"Train Loss={t_loss:.4f}  IoU={t_iou:.4f} | "
          f"Val   Loss={v_loss:.4f}  IoU={v_iou:.4f}")

"""## Part 8: Plot Loss & IoU Curves

"""

epochs_range = range(1, num_epochs + 1)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].plot(epochs_range, train_losses, label="Train Loss")
axes[0].plot(epochs_range, val_losses,   label="Val Loss")
axes[0].set_title("Loss Curve")
axes[0].set_xlabel("Epoch"); axes[0].set_ylabel("Loss")
axes[0].legend(); axes[0].grid(True)

axes[1].plot(epochs_range, train_ious, label="Train IoU")
axes[1].plot(epochs_range, val_ious,   label="Val IoU")
axes[1].set_title("Mean IoU Curve")
axes[1].set_xlabel("Epoch"); axes[1].set_ylabel("IoU")
axes[1].legend(); axes[1].grid(True)

plt.tight_layout()
plt.show()

"""## Part 9: Visualize Predictions vs Ground Truth

"""

model.eval()
sample_indices = random.sample(range(len(val_dataset)), 5)

for idx in sample_indices:
    img, mask = val_dataset[idx]

    with torch.no_grad():
        pred = model(img.unsqueeze(0).to(device))
        pred_mask = pred.argmax(dim=1).cpu().squeeze()

    fig, axes = plt.subplots(1, 3, figsize=(15, 5))

    axes[0].imshow(denormalize(img))
    axes[0].set_title("Satellite Image")
    axes[0].axis("off")

    axes[1].imshow(mask.cpu(), cmap="gray", vmin=0, vmax=1)
    axes[1].set_title("Ground Truth Mask")
    axes[1].axis("off")

    axes[2].imshow(pred_mask, cmap="gray", vmin=0, vmax=1)
    axes[2].set_title("Predicted Mask")
    axes[2].axis("off")

    plt.tight_layout()
    plt.show()